/**:
  ros__parameters::
    mujoco_plugins:
      kinect:
          type: mujoco_ros2_control_plugins/CameraPlugin
          camera_publish_rate: 30.0
          camera:
            policy: streaming
            frame_name: camera_color_optical_frame
            info_topic: color/camera_info
            image_topic: color/image_raw
            depth_topic: depth/image_raw

KapiBara/controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    motors:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    ears_controller:
      type: position_controllers/JointGroupPositionController

    imu_sensor_broadcaster:
        type: imu_sensor_broadcaster/IMUSensorBroadcaster

KapiBara/imu_sensor_broadcaster:
  ros__parameters:
    sensor_name: kapibara_imu # Must match URDF <sensor name="...">
    frame_id: KapiBara_imu_link # The TF frame it will publish data to

KapiBara/motors:
  ros__parameters:

    publish_rate: 10.0

    base_frame_id: KapiBara_base_link
    odom_frame_id: KapiBara_odom

    enable_odom_tf: True
    open_loop: False
    
    tf_frame_prefix_enable: False

    left_wheel_names: ['KapiBara_wheel_left1_joint']
    right_wheel_names: ['KapiBara_wheel_right3_joint']
    wheel_separation: 0.1
    wheel_radius: 0.024

    use_stamped_vel: False

KapiBara/ears_controller:
  ros__parameters:
    joints:
      - KapiBara_right_ear_joint
      - KapiBara_left_ear_joint